import type { Locale } from "./types.js";

export const TEXT = {
  zh: {
    usage: "用法：",
    commands: "命令：",
    options: "参数：",
    notes: "说明：",
    initDesc: "以 TUI 初始化当前目录或指定项目目录",
    helpDesc: "显示帮助",
    helpFlag: "显示帮助",
    versionFlag: "显示版本",
    forceFlag: "预设覆盖同名模板、skill 和全局 agent/config 条目",
    globalFlag: "预设将 skills 安装到用户目录下的 .agents/skills/",
    dryRunFlag: "预设先看 dry-run 结果，不落盘",
    langFlag: "预设输出语言：zh | en",
    tuiNote: "交互终端中，`oh-my-harness` 和 `oh-my-harness init` 默认进入 TUI。",
    seedNote: "命令行参数会作为 TUI 默认值；非交互环境中则直接执行。",
    unknownArg: "未知参数",
    missingLang: "缺少语言参数",
    missingCommand: "缺少命令",
    initHint: "当前参数不会默认触发 init。请显式使用 `init` 子命令。",
    unknownCommand: "未知命令",
    targetNotDirectory: "目标路径不是目录",
    initTarget: "目标目录:",
    mode: "模式:",
    modeDryRun: "dry-run 预览",
    modeApply: "实际写入",
    skillsTarget: "skills 目录:",
    globalConfig: "全局配置:",
    created: "创建",
    updated: "更新",
    replaced: "覆盖",
    patched: "补丁",
    skipped: "跳过",
    createTargetDir: "创建目标项目目录",
    initGitRepository: "初始化 Git 仓库",
    writeAgentsTemplate: "写入 AGENTS.md 模板",
    replaceAgentsBackup: "覆盖现有 AGENTS.md 备份文件",
    createAgentsBackup: "备份现有 AGENTS.md 到 agents.back.md",
    agentsAlreadyLatest: "AGENTS.md 已是最新模板",
    replaceAgentsTemplate: "直接覆盖 AGENTS.md 模板",
    writeGitignoreTemplate: "写入 .gitignore 模板块",
    updateGitignoreTemplate: "更新 .gitignore 模板块",
    gitignoreAlreadyLatest: ".gitignore 模板块已是最新",
    targetFileExistsNoForce: "目标文件已存在，未使用 --force",
    replaceTemplateFile: "按文件覆盖模板",
    createTemplateFile: "写入模板文件",
    createInitialTree: "生成初始 tree.md",
    refreshInitialTree: "刷新初始 tree.md",
    initialTreeAlreadyLatest: "初始 tree.md 已是最新",
    skillDirExistsNoForce: "skill 目录已存在，未使用 --force",
    installGlobalSkill: "安装全局 skill",
    installProjectSkill: "安装项目级 skill",
    globalConfigAgentExistsNoForce:
      "全局 config 已存在 agents.%s，未使用 --force",
    updateGlobalConfigAgent: "更新全局 config 的 agents.%s",
    createGlobalConfigAgent: "新增全局 config 的 agents.%s",
    initGlobalCodexConfig: "初始化全局 codex config",
    noGlobalConfigChange: "无全局 config 变更",
    agentMarkdownExistsNoForce: "agent markdown 已存在，未使用 --force",
    replaceAgentMarkdown: "覆盖 agent markdown",
    createAgentMarkdown: "写入 agent markdown",
    agentTomlExistsNoForce: "agent TOML 已存在，未使用 --force",
    patchAgentToml: "patch 覆盖 agent TOML",
    createAgentToml: "写入 agent TOML",
    migrationPromptLabel: "后续给 prompt 的提示:",
    migrationPrompt:
      "请对比 `AGENTS.md` 与 `agents.back.md`，只迁移仍有价值的项目级规则到新的 `AGENTS.md`，然后清理 `agents.back.md`。",
    tuiTitle: "oh-my-harness v%s · 初始化",
    tuiSubtitle: "使用方向键和 Enter 选择；按 q 或 Esc 退出。",
    tuiVersionCurrent: "当前版本: v%s",
    tuiUpdateAvailable: "发现新版本: v%s -> v%s",
    tuiUpdateCommand: "更新命令: %s",
    tuiStepLocale: "步骤 1/6 · 输出语言",
    tuiStepTarget: "步骤 2/6 · 目标目录",
    tuiStepScope: "步骤 3/6 · skills 写入位置",
    tuiStepForce: "步骤 4/6 · 冲突处理 (--force)",
    tuiStepDryRun: "步骤 5/6 · 执行方式 (dry-run)",
    tuiStepConfirm: "步骤 6/6 · 确认执行",
    tuiStepLocaleDesc: "先确定交互语言；后续步骤、说明和 dry-run 预览都会跟着切换。",
    tuiStepTargetDesc: "设置模板和项目级 skills 的目标目录；留空时直接使用当前目录。",
    tuiStepScopeDesc: "选择把 skills 写到当前项目的 `.agents/skills/`，还是写到用户目录下的全局 `.agents/skills/`。",
    tuiStepForceDesc: "如果同名模板、skill 或可 patch 配置已经存在，决定是直接覆盖/更新，还是保留现状。",
    tuiStepDryRunDesc: "选择先看完整的 dry-run 变更预览，还是直接实际写入。开启 dry-run 时只计算结果，不修改任何文件。",
    tuiStepConfirmDesc: "最后核对本次 init 的写入范围和 dry-run 结果，再开始执行。",
    tuiMenuTarget: "目标目录",
    tuiMenuScope: "skills 写入位置",
    tuiMenuForce: "冲突处理 (--force)",
    tuiMenuDryRun: "执行方式 (--dry-run)",
    tuiMenuLocale: "输出语言",
    tuiMenuRun: "开始执行",
    tuiMenuExit: "退出",
    tuiScopeProject: "项目级 (.agents/skills)",
    tuiScopeGlobal: "全局 (~/.agents/skills)",
    tuiForceOn: "开启",
    tuiForceOff: "关闭",
    tuiDryRunOn: "开启",
    tuiDryRunOff: "关闭",
    tuiEditPathTitle: "编辑目标目录",
    tuiEditPathHint: "输入路径后按 Enter 保存，Esc 返回。",
    tuiConfirmHint: "确认后开始执行；Esc 返回上一步。",
    tuiConfirmRun: "确认并执行",
    tuiPreviewTitle: "当前 dry-run 预览",
    tuiPreviewHint: "右侧始终显示完整的 dry-run 结果；这里只做预览，不会实际写入。",
    tuiPreviewLoading: "正在生成预览...",
    tuiPreviewError: "预览失败",
    tuiSidebarTitle: "当前步骤说明",
    tuiRunning: "正在执行初始化...",
    tuiDone: "执行完成。按 Enter、q 或 Esc 退出。",
    tuiFailed: "执行失败。按 Enter、q 或 Esc 退出。",
    tuiBack: "返回",
  },
  en: {
    usage: "Usage:",
    commands: "Commands:",
    options: "Options:",
    notes: "Notes:",
    initDesc: "Initialize the current directory or a target project directory using TUI",
    helpDesc: "Show help",
    helpFlag: "Show help",
    versionFlag: "Show version",
    forceFlag: "Preseed overwrite for same-name templates, skills, and global agent/config entries",
    globalFlag: "Preseed skills install into the user's .agents/skills/ directory",
    dryRunFlag: "Preseed dry-run preview; do not write files",
    langFlag: "Preseed output language: zh | en",
    tuiNote: "In an interactive terminal, `oh-my-harness` and `oh-my-harness init` open the TUI by default.",
    seedNote: "CLI options seed the TUI; in non-interactive environments they execute directly.",
    unknownArg: "Unknown argument",
    missingLang: "Missing language argument",
    missingCommand: "Missing command",
    initHint:
      "These options do not implicitly run init. Please use the `init` subcommand explicitly.",
    unknownCommand: "Unknown command",
    targetNotDirectory: "Target path is not a directory",
    initTarget: "init target:",
    mode: "mode:",
    modeDryRun: "dry-run preview",
    modeApply: "write files",
    skillsTarget: "skills target:",
    globalConfig: "global config:",
    created: "created",
    updated: "updated",
    replaced: "replaced",
    patched: "patched",
    skipped: "skipped",
    createTargetDir: "create target project directory",
    initGitRepository: "initialize Git repository",
    writeAgentsTemplate: "write AGENTS.md template",
    replaceAgentsBackup: "replace existing AGENTS.md backup file",
    createAgentsBackup: "backup existing AGENTS.md to agents.back.md",
    agentsAlreadyLatest: "AGENTS.md is already up to date",
    replaceAgentsTemplate: "replace AGENTS.md directly",
    writeGitignoreTemplate: "write .gitignore template block",
    updateGitignoreTemplate: "update .gitignore template block",
    gitignoreAlreadyLatest: ".gitignore template block is already up to date",
    targetFileExistsNoForce: "target file already exists; --force not set",
    replaceTemplateFile: "replace template file",
    createTemplateFile: "write template file",
    createInitialTree: "generate initial tree.md",
    refreshInitialTree: "refresh initial tree.md",
    initialTreeAlreadyLatest: "initial tree.md is already up to date",
    skillDirExistsNoForce: "skill directory already exists; --force not set",
    installGlobalSkill: "install global skill",
    installProjectSkill: "install project skill",
    globalConfigAgentExistsNoForce:
      "global config already has agents.%s; --force not set",
    updateGlobalConfigAgent: "update global config agents.%s",
    createGlobalConfigAgent: "create global config agents.%s",
    initGlobalCodexConfig: "initialize global codex config",
    noGlobalConfigChange: "no global config changes",
    agentMarkdownExistsNoForce: "agent markdown already exists; --force not set",
    replaceAgentMarkdown: "replace agent markdown",
    createAgentMarkdown: "write agent markdown",
    agentTomlExistsNoForce: "agent TOML already exists; --force not set",
    patchAgentToml: "patch agent TOML",
    createAgentToml: "write agent TOML",
    migrationPromptLabel: "prompt for next step:",
    migrationPrompt:
      "Compare `AGENTS.md` with `agents.back.md`, migrate only still-useful project-level rules into the new `AGENTS.md`, then remove `agents.back.md`.",
    tuiTitle: "oh-my-harness v%s · init",
    tuiSubtitle:
      "Use arrow keys and Enter to select; press q or Esc to exit.",
    tuiVersionCurrent: "Current version: v%s",
    tuiUpdateAvailable: "New version available: v%s -> v%s",
    tuiUpdateCommand: "Update command: %s",
    tuiStepLocale: "Step 1/6 · Output language",
    tuiStepTarget: "Step 2/6 · Target directory",
    tuiStepScope: "Step 3/6 · Skills destination",
    tuiStepForce: "Step 4/6 · Conflict handling (--force)",
    tuiStepDryRun: "Step 5/6 · Execution mode (dry-run)",
    tuiStepConfirm: "Step 6/6 · Confirm",
    tuiStepLocaleDesc: "Choose the interaction language first; later steps, descriptions, and dry-run preview follow it.",
    tuiStepTargetDesc: "Set the target directory for templates and project-level skills; leave empty to use the current directory.",
    tuiStepScopeDesc: "Choose whether skills are written into the project's `.agents/skills/` or the user's global `.agents/skills/`.",
    tuiStepForceDesc: "If same-name templates, skills, or patchable config already exist, decide whether to overwrite/update them or leave them as-is.",
    tuiStepDryRunDesc: "Choose whether to inspect the full dry-run preview first or write files immediately. With dry-run on, nothing is modified.",
    tuiStepConfirmDesc: "Review the final init scope and dry-run result before execution.",
    tuiMenuTarget: "Target directory",
    tuiMenuScope: "Skills destination",
    tuiMenuForce: "Conflict handling (--force)",
    tuiMenuDryRun: "Execution mode (--dry-run)",
    tuiMenuLocale: "Output language",
    tuiMenuRun: "Run init",
    tuiMenuExit: "Exit",
    tuiScopeProject: "Project (.agents/skills)",
    tuiScopeGlobal: "Global (~/.agents/skills)",
    tuiForceOn: "On",
    tuiForceOff: "Off",
    tuiDryRunOn: "On",
    tuiDryRunOff: "Off",
    tuiEditPathTitle: "Edit target directory",
    tuiEditPathHint: "Enter a path and press Enter to save, Esc to go back.",
    tuiConfirmHint: "Confirm to execute; Esc returns to the previous step.",
    tuiConfirmRun: "Confirm and run",
    tuiPreviewTitle: "Current dry-run preview",
    tuiPreviewHint: "The right pane always shows the full dry-run result; previewing here never writes files.",
    tuiPreviewLoading: "Generating preview...",
    tuiPreviewError: "Preview failed",
    tuiSidebarTitle: "Current step",
    tuiRunning: "Running init...",
    tuiDone: "Done. Press Enter, q, or Esc to exit.",
    tuiFailed: "Failed. Press Enter, q, or Esc to exit.",
    tuiBack: "Back",
  },
} as const;

export function formatText(
  locale: Locale,
  key: keyof typeof TEXT.zh,
  ...args: string[]
): string {
  let value: string = TEXT[locale][key];
  for (const arg of args) {
    value = value.replace("%s", arg);
  }
  return value;
}
